### ISSUE TITLE
Plot Nodal stress Error

### ISSUE THREAD

**Issue by sulei27** [ansys/pymapdl-reader#263]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

mapdl.post_processing.nodal_eqv_stress()

![2023-05-30_134925](https://github.com/ansys/pymapdl-reader/assets/127292992/c4385a34-99bd-4231-bc66-76419a2b24d3)

### 📝 Steps to reproduce

When I am trying to plot Nodal Stress using the commands: "result.plot_nodal_stress(0)" or "mapdl.post_processing.nodal_eqv_stress()"
  it gives me the following Error.!

ERROR:  CRITICAL -  -  logging - handle_exception - Uncaught exception
Traceback (most recent call last):
  File "C:\Users\dell\PycharmProjects\pythonProject15\gf.py", line 178, in <module>
    result.plot_nodal_stress(0, comp='x')
  File "E:\python3.10\lib\site-packages\ansys\mapdl\reader\rst.py", line 3433, in plot_nodal_stress
    return self._plot_nodal_result(
  File "E:\python3.10\lib\site-packages\ansys\mapdl\reader\rst.py", line 4894, in _plot_nodal_result
    _, result = self._nodal_result(rnum, result_type)
  File "E:\python3.10\lib\site-packages\ansys\mapdl\reader\rst.py", line 3707, in _nodal_result
    raise ValueError(
ValueError: Result Nodal stresses (ENS) is not available in this result file.

Process finished with exit code 1

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2021 R2

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
Pyansys


IDE : Pycharm
```

**Comment by mikerife** [comment]
Hi @sulei27 It looks like there are no element nodal stresses in the result file to plot.  To double check print the result object:

```python
print(result)
```
Which will produce a listing like shown here:

https://reader.docs.pyansys.com/user_guide/loading_results.html#result-properties

ENS should not show up (i.e. not available)...can you confirm.  

Mike
